---
AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB tables and indexes for the Bits & Bobs application

Parameters:
  Environment:
    Type: String
    Default: Development
    Description: The environment for which the resources are being created
    AllowedValues:
      - Development
      - Staging
      - Production

Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    # checkov:skip=CKV_AWS_28:Ensure Dynamodb point in time recovery (backup) is enabled
    # checkov:skip=CKV_AWS_119:Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK
    Properties:
      TableName: !Sub "${Environment}-BitsAndBobs"
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: NormalizedEmailAddress
          AttributeType: S
        - AttributeName: NormalizedUsername
          AttributeType: S
        - AttributeName: AuctionStatus
          AttributeType: N
        - AttributeName: EndDateUtcTimeStamp
          AttributeType: N
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UsersByNormalizedEmailAddress
          KeySchema:
            - AttributeName: NormalizedEmailAddress
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UsersByNormalizedUsername
          KeySchema:
            - AttributeName: NormalizedUsername
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: AuctionsByStatus
          KeySchema:
            - AttributeName: AuctionStatus
              KeyType: HASH
            - AttributeName: EndDateUtcTimeStamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Value: !Ref DynamoDbTable
  TableArn:
    Value: !GetAtt DynamoDbTable.Arn

