# Default values for bitsandbobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
# replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  #repository: ghcr.io/bitsandbobs-api
  repository: "public.ecr.aws/l6m2t8p7/docker-2048"
  tag: "latest"
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  #tag: ""

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - NET_RAW
  seccompProfile:
    type: RuntimeDefault

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  ports:
    - name: http
      port: 80
  #    targetPort: 8080
      targetPort: 80
      protocol: TCP
  #  - name: http-diag
  #    port: 3434
  #    targetPort: 3434
  #    protocol: TCP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# livenessProbe:
#   httpGet:
#     path: /livez
#     port: http-diag
# readinessProbe:
#   httpGet:
#     path: /readyz
#     port: http-diag

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector:
  karpenter.sh/capacity-type: spot

tolerations:
  - key: "spot"
    value: "true"
    effect: "NoSchedule"

affinity: {}

# The name of the EKS cluster
eksClusterName: "EksCluster-Staging"

# The name of the role used by nodes
nodeIamRoleName: "AmazonEKSAutoNodeRole"
