//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface UserContextResponse {
    readonly isAuthenticated?: boolean;
    readonly username?: string | undefined;
    readonly emailAddress?: string | undefined;
}

export interface EmailResponse {
    readonly recipient: string;
    readonly type: string;
    readonly body: string;
    readonly sentAt: Date;
}

export interface ProblemDetails {
    readonly type?: string | undefined;
    readonly title?: string | undefined;
    readonly status?: number | undefined;
    readonly detail?: string | undefined;
    readonly instance?: string | undefined;

    [key: string]: any;
}

export interface HttpValidationProblemDetails extends ProblemDetails {
    errors?: { [key: string]: string[]; };

    [key: string]: any;
}

export interface RegisterRequest {
    readonly email?: string;
    readonly password?: string;
}

export interface AccessTokenResponse {
    readonly tokenType?: string;
    readonly accessToken?: string;
    readonly expiresIn?: number;
    readonly refreshToken?: string;
}

export interface LoginRequest {
    readonly email?: string;
    readonly password?: string;
    readonly twoFactorCode?: string | undefined;
    readonly twoFactorRecoveryCode?: string | undefined;
}

export interface RefreshRequest {
    readonly refreshToken?: string;
}

export interface ResendConfirmationEmailRequest {
    readonly email?: string;
}

export interface ForgotPasswordRequest {
    readonly email?: string;
}

export interface ResetPasswordRequest {
    readonly email?: string;
    readonly resetCode?: string;
    readonly newPassword?: string;
}

export interface TwoFactorResponse {
    readonly sharedKey?: string;
    readonly recoveryCodesLeft?: number;
    readonly recoveryCodes?: string[] | undefined;
    readonly isTwoFactorEnabled?: boolean;
    readonly isMachineRemembered?: boolean;
}

export interface TwoFactorRequest {
    readonly enable?: boolean | undefined;
    readonly twoFactorCode?: string | undefined;
    readonly resetSharedKey?: boolean;
    readonly resetRecoveryCodes?: boolean;
    readonly forgetMachine?: boolean;
}

export interface InfoResponse {
    readonly email?: string;
    readonly isEmailConfirmed?: boolean;
}

export interface InfoRequest {
    readonly newEmail?: string | undefined;
    readonly newPassword?: string | undefined;
    readonly oldPassword?: string | undefined;
}

export interface DetailsResponse {
    readonly emailAddress: string;
    readonly displayName: string;
    readonly firstName?: string | undefined;
    readonly lastName?: string | undefined;
}

export interface DetailsRequest {
    readonly displayName?: string | undefined;
    readonly firstName?: string | undefined;
    readonly lastName?: string | undefined;
}