#!/bin/bash
#
# Arguments
# $1 - Previous HEAD
# $2 - New HEAD
# $3 - 1 if checking out a branch, 0 if checking out something else, such as a file (rollbacks)

if [ "1" == "$3" ]; then
    # When checking out a new branch, run yarn to update cliental modules
    declare GIT_ROOT="$(git rev-parse --show-toplevel)"
    pushd "${GIT_ROOT}/src/BitsAndBobs/clientapp" > /dev/null
    trap "popd > /dev/null" EXIT
    npx -y yarn install
fi
