#!/bin/bash
#
# Hook script that runs validation on modified files before a commit.  Called by "git
# commit" before anything has been committed.  If this script exits with a non-zero status ,
# nothing will be committed.
#
set -e

# If a merge is in process, we don't want to do the lint step
if [[ -f '.git/MERGE_HEAD' ]]; then
    exit 0
fi

# Make sure we pop any pushed directories
dirstack_initial_size=$(dirs -p | wc -l)
trap 'while [ "$(dirs -p | wc -l)" -gt "$dirstack_initial_size" ]; do popd > /dev/null; done' EXIT

declare GIT_ROOT="$(git rev-parse --show-toplevel)"

# Check for any staged file paths that include clientapp (case-insensitive)
if git diff --cached --name-only --diff-filter=ADMR HEAD | grep -qiE '^src/BitsAndBobs/clientapp/'; then

    pushd "${GIT_ROOT}/src/BitsAndBobs/clientapp" > /dev/null
    yarn lint-staged -q
fi

# Validate CFN templates
if git diff --cached --name-only --diff-filter=ADMR HEAD | grep -qiE --include=\*.yaml '^src/Infrastructure/'; then

    pushd "${GIT_ROOT}/src/Infrastructure" > /dev/null
    docker run --platform linux/amd64 -v `pwd`:/data -w /data --rm public.ecr.aws/mysteriouscode/cfn-lint:latest cfn-lint --info *.yaml
    docker run --platform linux/amd64 -v `pwd`:/data -w /data --rm bridgecrew/checkov --quiet --framework cloudformation --directory ./
fi
