---
apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
  labels:
    {{- include "bitsandbobs.labels" . | nindent 4 }}
spec:
  scheme: internal

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  annotations:
    # Use this annotation to set an IngressClass as Default
    # If an Ingress doesn't specify a class, it will use the Default
    ingressclass.kubernetes.io/is-default-class: "true"
  labels:
    {{- include "bitsandbobs.labels" . | nindent 4 }}
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bitsandbobs.fullname" . }}
  labels:
    {{- include "bitsandbobs.labels" . | nindent 4 }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bitsandbobs.fullname" . }}
                port:
                  number: 80
