name: Container cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "* 20 * * *"  # every day at 8pm UTC

env:
  imageName: bitsandbobs-api

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old/un-tagged container images
    steps:
      - name: Delete untagged images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ env.imageName }}
          tag-selection: untagged
          cut-off: 1m
          dry-run: true
      - name: Retain only three tagged images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ env.imageName }}
          tag-selection: tagged
          keep-n-most-recent: 3
          cut-off: 1m
          dry-run: true
