name: Container cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "* 20 * * *"  # every day at 8pm UTC

env:
  imageName: bitsandbobs-api

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old/un-tagged container images
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete untagged images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ env.imageName }}
          tag-selection: untagged
          cut-off: 1m
      - name: Retain only three tagged images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ env.imageName }}
          tag-selection: tagged
          keep-n-most-recent: 3
          cut-off: 1m
