name: CI - Infrastructure Validation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Infrastructure/cfn/**/*.yaml'
      - 'src/Infrastructure/helm/**/*.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/Infrastructure/cfn/**/*.yaml'
      - 'src/Infrastructure/helm/**/*.yaml'

jobs:
  checkov:
    name: Validate with checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Scan with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: './src/Infrastructure/cfn/'
          framework: cloudformation
          quiet: true

  cfnLint:
    name: Validate with cfn-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cfn-lint with latest version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the cfn-lint version & run linter
        run: |
          shopt -s globstar # enable globbing
          cfn-lint --version
          cfn-lint -t ./src/Infrastructure/cfn/**/*.yaml

  helm:
    name: Validate with helm lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Setup cfn-lint with latest version
      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
      - name: Run linter
        run: helm lint src/Infrastructure/helm/bitsandbobs


